/* This file is automatically generated.  DO NOT EDIT! */
extern ld_emulation_xfer_type ld_armelf_linux_emulation;
extern ld_emulation_xfer_type ld_armelf_emulation;

#define EMULATION_LIST \
  &ld_armelf_linux_emulation, \
  &ld_armelf_emulation, \
  0
