asdata.o: asdata.c asm.h
asexpr.o: asexpr.c asm.h
aslex.o: aslex.c asm.h
aslist.o: aslist.c asm.h
asmain.o: asmain.c asm.h z80.h
asout.o: asout.c asm.h
assubr.o: assubr.c asm.h
assym.o: assym.c asm.h
z80adr.o: z80adr.c asm.h z80.h
z80ext.o: z80ext.c asm.h z80.h
z80mch.o: z80mch.c asm.h z80.h
z80pst.o: z80pst.c asm.h z80.h
